/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateWhishlistArgs } from "./CreateWhishlistArgs";
import { UpdateWhishlistArgs } from "./UpdateWhishlistArgs";
import { DeleteWhishlistArgs } from "./DeleteWhishlistArgs";
import { WhishlistCountArgs } from "./WhishlistCountArgs";
import { WhishlistFindManyArgs } from "./WhishlistFindManyArgs";
import { WhishlistFindUniqueArgs } from "./WhishlistFindUniqueArgs";
import { Whishlist } from "./Whishlist";
import { Listing } from "../../listing/base/Listing";
import { User } from "../../user/base/User";
import { WhishlistService } from "../whishlist.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Whishlist)
export class WhishlistResolverBase {
  constructor(
    protected readonly service: WhishlistService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Whishlist",
    action: "read",
    possession: "any",
  })
  async _whishlistsMeta(
    @graphql.Args() args: WhishlistCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Whishlist])
  @nestAccessControl.UseRoles({
    resource: "Whishlist",
    action: "read",
    possession: "any",
  })
  async whishlists(
    @graphql.Args() args: WhishlistFindManyArgs
  ): Promise<Whishlist[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Whishlist, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Whishlist",
    action: "read",
    possession: "own",
  })
  async whishlist(
    @graphql.Args() args: WhishlistFindUniqueArgs
  ): Promise<Whishlist | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Whishlist)
  @nestAccessControl.UseRoles({
    resource: "Whishlist",
    action: "create",
    possession: "any",
  })
  async createWhishlist(
    @graphql.Args() args: CreateWhishlistArgs
  ): Promise<Whishlist> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        listing: {
          connect: args.data.listing,
        },

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Whishlist)
  @nestAccessControl.UseRoles({
    resource: "Whishlist",
    action: "update",
    possession: "any",
  })
  async updateWhishlist(
    @graphql.Args() args: UpdateWhishlistArgs
  ): Promise<Whishlist | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          listing: {
            connect: args.data.listing,
          },

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Whishlist)
  @nestAccessControl.UseRoles({
    resource: "Whishlist",
    action: "delete",
    possession: "any",
  })
  async deleteWhishlist(
    @graphql.Args() args: DeleteWhishlistArgs
  ): Promise<Whishlist | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Listing, {
    nullable: true,
    name: "listing",
  })
  @nestAccessControl.UseRoles({
    resource: "Listing",
    action: "read",
    possession: "any",
  })
  async resolveFieldListing(
    @graphql.Parent() parent: Whishlist
  ): Promise<Listing | null> {
    const result = await this.service.getListing(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async resolveFieldUser(
    @graphql.Parent() parent: Whishlist
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
